export const allegroCategories = [
    { id: "spring", name: "Czas na wiosenne zakupy", icon: "/placeholder.svg?height=80&width=80" },
    { id: "business", name: "Zakupy dla firm", icon: "/placeholder.svg?height=80&width=80" },
    { id: "coupons", name: "Polecaj i odbieraj kupony", icon: "/placeholder.svg?height=80&width=80" },
    { id: "delivery", name: "Dostawy i zwroty za 0 zł", icon: "/placeholder.svg?height=80&width=80" },
    { id: "pilates", name: "Akcesoria do pilates", icon: "/placeholder.svg?height=80&width=80" },
    { id: "garden-tools", name: "Narzędzia ogrodnicze", icon: "/placeholder.svg?height=80&width=80" },
    { id: "garden-furniture", name: "Meble ogrodowe", icon: "/placeholder.svg?height=80&width=80" },
    { id: "sports-shoes", name: "Buty sportowe", icon: "/placeholder.svg?height=80&width=80" },
    { id: "rollers", name: "Rolki", icon: "/placeholder.svg?height=80&width=80" },
    { id: "motorcycles", name: "Motoryzacja", icon: "/placeholder.svg?height=80&width=80" },
    { id: "home-garden", name: "Dom i ogród", icon: "/placeholder.svg?height=80&width=80" },
    { id: "fashion", name: "Moda", icon: "/placeholder.svg?height=80&width=80" },
  ]

export const allegroProducts = [
  {
    id: "tire1",
    name: "Opona letnia Premiori Solazo S Plus 225/45R17 91 W",
    price: 200.0,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "garden1",
    name: "WARZYWNIK SKRZYNIA NA WARZYWA RABATA KWIATOWA SKŁADANA",
    price: 85.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa w środę",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "pot1",
    name: "KOCIOŁEK ŻELIWNY 8 L GARNEK Myśliwski Węgierski na Ognisko",
    price: 159.98,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "mop1",
    name: "Mop parowy Karcher SC 1 Upright 2x Końcówka 1.513-360.0",
    price: 269.75,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "grill1",
    name: "STAŁOWY GRILL OGRODOWY BEZ POKRYWY WĘGLOWY",
    price: 119.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa w środę",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "tire2",
    name: "Opona letnia 195/65R15 91H Nokia Wetproof 1",
    price: 205.0,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "headphones1",
    name: "Słuchawki bezprzewodowe nauszne JBL Tune 710BT Czarne",
    price: 180.54,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "bike1",
    name: "ROWER GÓRSKI MĘSKI MTB 27,5 CALI ALUMINIOWY LEKKI",
    price: 999.0,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
  {
    id: "box1",
    name: "SKRZYNIA OGRODOWA 270 LITRÓW BALKON TARAS PODUSZKI",
    price: 249.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    smart: true,
    delivery: "dostawa we wtorek",
    guarantee: "Gwarancja najniższej ceny",
  },
]