export const makroProducts = [
  {
    id: "product1",
    name: "Pomidory w puszce San Marzano",
    price: 14.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product2",
    name: "Olej rzepakowy 5L",
    price: 58.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product3",
    name: "Mąka pszenna typ 500 25kg",
    price: 89.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product4",
    name: "Udo z kurczaka 5kg",
    price: 65.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product5",
    name: "Schab wieprzowy b/k 1kg",
    price: 18.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product6",
    name: "Filet z kurczaka 1kg",
    price: 12.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product7",
    name: "Wołowina antrykot 1kg",
    price: 36.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
  {
    id: "product8",
    name: "Filet z indyka 1kg",
    price: 42.99,
    image: "/placeholder.svg?height=200&width=200",
    quantity: Math.floor(Math.random() * 46) + 5,
    category: "gastronomy",
  },
]